language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t myimage -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true myimage npm run test
after_success:
  - docker build -t robbinakm/client ./client
  - docker build -t robbinakm/nginx ./nginx
  - docker build -t robbinakm/server ./server
  - docker build -t robbinakm/worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password--stdin
  - docker push robbinakm/client
  - docker push robbinakm/nginx
  - docker push robbinakm/server
  - docker push robbinakm/worker
